/**
 * Samsara API
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SamsaraApi);
  }
}(this, function(expect, SamsaraApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SamsaraApi.DispatchJobsResponseDispatchJobs();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DispatchJobsResponseDispatchJobs', function() {
    it('should create an instance of DispatchJobsResponseDispatchJobs', function() {
      // uncomment below and update the code to test DispatchJobsResponseDispatchJobs
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be.a(SamsaraApi.DispatchJobsResponseDispatchJobs);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be();
    });

    it('should have the property externalIdentifier (base name: "external_identifier")', function() {
      // uncomment below and update the code to test the property externalIdentifier
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be();
    });

    it('should have the property orgId (base name: "org_id")', function() {
      // uncomment below and update the code to test the property orgId
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be();
    });

    it('should have the property groupId (base name: "group_id")', function() {
      // uncomment below and update the code to test the property groupId
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be();
    });

    it('should have the property driverId (base name: "driver_id")', function() {
      // uncomment below and update the code to test the property driverId
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be();
    });

    it('should have the property vehicleId (base name: "vehicle_id")', function() {
      // uncomment below and update the code to test the property vehicleId
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be();
    });

    it('should have the property jobState (base name: "job_state")', function() {
      // uncomment below and update the code to test the property jobState
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be();
    });

    it('should have the property scheduledArrivalTimeMs (base name: "scheduled_arrival_time_ms")', function() {
      // uncomment below and update the code to test the property scheduledArrivalTimeMs
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be();
    });

    it('should have the property startedAtMs (base name: "started_at_ms")', function() {
      // uncomment below and update the code to test the property startedAtMs
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be();
    });

    it('should have the property completedAtMs (base name: "completed_at_ms")', function() {
      // uncomment below and update the code to test the property completedAtMs
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be();
    });

    it('should have the property cancelledAtMs (base name: "cancelled_at_ms")', function() {
      // uncomment below and update the code to test the property cancelledAtMs
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be();
    });

    it('should have the property jobCreatedAtMs (base name: "job_created_at_ms")', function() {
      // uncomment below and update the code to test the property jobCreatedAtMs
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be();
    });

    it('should have the property notes (base name: "notes")', function() {
      // uncomment below and update the code to test the property notes
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be();
    });

    it('should have the property destinationName (base name: "destination_name")', function() {
      // uncomment below and update the code to test the property destinationName
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be();
    });

    it('should have the property destinationAddress (base name: "destination_address")', function() {
      // uncomment below and update the code to test the property destinationAddress
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be();
    });

    it('should have the property destinationLat (base name: "destination_lat")', function() {
      // uncomment below and update the code to test the property destinationLat
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be();
    });

    it('should have the property destinationLng (base name: "destination_lng")', function() {
      // uncomment below and update the code to test the property destinationLng
      //var instane = new SamsaraApi.DispatchJobsResponseDispatchJobs();
      //expect(instance).to.be();
    });

  });

}));
