/**
 * Samsara API
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SamsaraApi);
  }
}(this, function(expect, SamsaraApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SamsaraApi.HistoryParam();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HistoryParam', function() {
    it('should create an instance of HistoryParam', function() {
      // uncomment below and update the code to test HistoryParam
      //var instane = new SamsaraApi.HistoryParam();
      //expect(instance).to.be.a(SamsaraApi.HistoryParam);
    });

    it('should have the property groupId (base name: "groupId")', function() {
      // uncomment below and update the code to test the property groupId
      //var instane = new SamsaraApi.HistoryParam();
      //expect(instance).to.be();
    });

    it('should have the property startMs (base name: "startMs")', function() {
      // uncomment below and update the code to test the property startMs
      //var instane = new SamsaraApi.HistoryParam();
      //expect(instance).to.be();
    });

    it('should have the property endMs (base name: "endMs")', function() {
      // uncomment below and update the code to test the property endMs
      //var instane = new SamsaraApi.HistoryParam();
      //expect(instance).to.be();
    });

    it('should have the property stepMs (base name: "stepMs")', function() {
      // uncomment below and update the code to test the property stepMs
      //var instane = new SamsaraApi.HistoryParam();
      //expect(instance).to.be();
    });

    it('should have the property series (base name: "series")', function() {
      // uncomment below and update the code to test the property series
      //var instane = new SamsaraApi.HistoryParam();
      //expect(instance).to.be();
    });

    it('should have the property fillMissing (base name: "fillMissing")', function() {
      // uncomment below and update the code to test the property fillMissing
      //var instane = new SamsaraApi.HistoryParam();
      //expect(instance).to.be();
    });

  });

}));
