/**
 * Samsara API
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SamsaraApi);
  }
}(this, function(expect, SamsaraApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SamsaraApi.HosLogsResponseLogs();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HosLogsResponseLogs', function() {
    it('should create an instance of HosLogsResponseLogs', function() {
      // uncomment below and update the code to test HosLogsResponseLogs
      //var instane = new SamsaraApi.HosLogsResponseLogs();
      //expect(instance).to.be.a(SamsaraApi.HosLogsResponseLogs);
    });

    it('should have the property groupId (base name: "groupId")', function() {
      // uncomment below and update the code to test the property groupId
      //var instane = new SamsaraApi.HosLogsResponseLogs();
      //expect(instance).to.be();
    });

    it('should have the property vehicleId (base name: "vehicleId")', function() {
      // uncomment below and update the code to test the property vehicleId
      //var instane = new SamsaraApi.HosLogsResponseLogs();
      //expect(instance).to.be();
    });

    it('should have the property driverId (base name: "driverId")', function() {
      // uncomment below and update the code to test the property driverId
      //var instane = new SamsaraApi.HosLogsResponseLogs();
      //expect(instance).to.be();
    });

    it('should have the property logStartMs (base name: "logStartMs")', function() {
      // uncomment below and update the code to test the property logStartMs
      //var instane = new SamsaraApi.HosLogsResponseLogs();
      //expect(instance).to.be();
    });

    it('should have the property statusType (base name: "statusType")', function() {
      // uncomment below and update the code to test the property statusType
      //var instane = new SamsaraApi.HosLogsResponseLogs();
      //expect(instance).to.be();
    });

    it('should have the property locCity (base name: "locCity")', function() {
      // uncomment below and update the code to test the property locCity
      //var instane = new SamsaraApi.HosLogsResponseLogs();
      //expect(instance).to.be();
    });

    it('should have the property locState (base name: "locState")', function() {
      // uncomment below and update the code to test the property locState
      //var instane = new SamsaraApi.HosLogsResponseLogs();
      //expect(instance).to.be();
    });

    it('should have the property locLat (base name: "locLat")', function() {
      // uncomment below and update the code to test the property locLat
      //var instane = new SamsaraApi.HosLogsResponseLogs();
      //expect(instance).to.be();
    });

    it('should have the property locLng (base name: "locLng")', function() {
      // uncomment below and update the code to test the property locLng
      //var instane = new SamsaraApi.HosLogsResponseLogs();
      //expect(instance).to.be();
    });

  });

}));
