/**
 * Samsara API
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SamsaraApi) {
      root.SamsaraApi = {};
    }
    root.SamsaraApi.GetDispatchJobsParam = factory(root.SamsaraApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetDispatchJobsParam model module.
   * @module models/GetDispatchJobsParam
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GetDispatchJobsParam</code>.
   * @alias module:models/GetDispatchJobsParam
   * @class
   * @param groupId {Integer} 
   * @param durationSeconds {Integer} 
   */
  var exports = function(groupId, durationSeconds) {
    var _this = this;

    _this['group_id'] = groupId;

    _this['duration_seconds'] = durationSeconds;
  };

  /**
   * Constructs a <code>GetDispatchJobsParam</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:models/GetDispatchJobsParam} obj Optional instance to populate.
   * @return {module:models/GetDispatchJobsParam} The populated <code>GetDispatchJobsParam</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('group_id')) {
        obj['group_id'] = ApiClient.convertToType(data['group_id'], 'Integer');
      }
      if (data.hasOwnProperty('job_created_at_max_ms')) {
        obj['job_created_at_max_ms'] = ApiClient.convertToType(data['job_created_at_max_ms'], 'Integer');
      }
      if (data.hasOwnProperty('duration_seconds')) {
        obj['duration_seconds'] = ApiClient.convertToType(data['duration_seconds'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {Integer} group_id
   */
  exports.prototype['group_id'] = undefined;
  /**
   * @member {Integer} job_created_at_max_ms
   */
  exports.prototype['job_created_at_max_ms'] = undefined;
  /**
   * @member {Integer} duration_seconds
   */
  exports.prototype['duration_seconds'] = undefined;



  return exports;
}));


