/**
 * Samsara API
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SamsaraApi) {
      root.SamsaraApi = {};
    }
    root.SamsaraApi.HosLogsResponseLogs = factory(root.SamsaraApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The HosLogsResponseLogs model module.
   * @module models/HosLogsResponseLogs
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>HosLogsResponseLogs</code>.
   * @alias module:models/HosLogsResponseLogs
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>HosLogsResponseLogs</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:models/HosLogsResponseLogs} obj Optional instance to populate.
   * @return {module:models/HosLogsResponseLogs} The populated <code>HosLogsResponseLogs</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('groupId')) {
        obj['groupId'] = ApiClient.convertToType(data['groupId'], 'Integer');
      }
      if (data.hasOwnProperty('vehicleId')) {
        obj['vehicleId'] = ApiClient.convertToType(data['vehicleId'], 'Integer');
      }
      if (data.hasOwnProperty('driverId')) {
        obj['driverId'] = ApiClient.convertToType(data['driverId'], 'Integer');
      }
      if (data.hasOwnProperty('logStartMs')) {
        obj['logStartMs'] = ApiClient.convertToType(data['logStartMs'], 'Integer');
      }
      if (data.hasOwnProperty('statusType')) {
        obj['statusType'] = ApiClient.convertToType(data['statusType'], 'String');
      }
      if (data.hasOwnProperty('locCity')) {
        obj['locCity'] = ApiClient.convertToType(data['locCity'], 'String');
      }
      if (data.hasOwnProperty('locState')) {
        obj['locState'] = ApiClient.convertToType(data['locState'], 'String');
      }
      if (data.hasOwnProperty('locLat')) {
        obj['locLat'] = ApiClient.convertToType(data['locLat'], 'Number');
      }
      if (data.hasOwnProperty('locLng')) {
        obj['locLng'] = ApiClient.convertToType(data['locLng'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Integer} groupId
   */
  exports.prototype['groupId'] = undefined;
  /**
   * @member {Integer} vehicleId
   */
  exports.prototype['vehicleId'] = undefined;
  /**
   * @member {Integer} driverId
   */
  exports.prototype['driverId'] = undefined;
  /**
   * @member {Integer} logStartMs
   */
  exports.prototype['logStartMs'] = undefined;
  /**
   * @member {String} statusType
   */
  exports.prototype['statusType'] = undefined;
  /**
   * @member {String} locCity
   */
  exports.prototype['locCity'] = undefined;
  /**
   * @member {String} locState
   */
  exports.prototype['locState'] = undefined;
  /**
   * @member {Number} locLat
   */
  exports.prototype['locLat'] = undefined;
  /**
   * @member {Number} locLng
   */
  exports.prototype['locLng'] = undefined;



  return exports;
}));


