/**
 * Samsara API
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SamsaraApi) {
      root.SamsaraApi = {};
    }
    root.SamsaraApi.SensorshistorySeries = factory(root.SamsaraApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SensorshistorySeries model module.
   * @module models/SensorshistorySeries
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SensorshistorySeries</code>.
   * @alias module:models/SensorshistorySeries
   * @class
   * @param widgetId {Integer} 
   * @param field {module:models/SensorshistorySeries.FieldEnum} 
   */
  var exports = function(widgetId, field) {
    var _this = this;

    _this['widgetId'] = widgetId;
    _this['field'] = field;
  };

  /**
   * Constructs a <code>SensorshistorySeries</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:models/SensorshistorySeries} obj Optional instance to populate.
   * @return {module:models/SensorshistorySeries} The populated <code>SensorshistorySeries</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('widgetId')) {
        obj['widgetId'] = ApiClient.convertToType(data['widgetId'], 'Integer');
      }
      if (data.hasOwnProperty('field')) {
        obj['field'] = ApiClient.convertToType(data['field'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Integer} widgetId
   */
  exports.prototype['widgetId'] = undefined;
  /**
   * @member {module:models/SensorshistorySeries.FieldEnum} field
   */
  exports.prototype['field'] = undefined;


  /**
   * Allowed values for the <code>field</code> property.
   * @enum {String}
   * @readonly
   */
  exports.FieldEnum = {
    /**
     * value: "ambientTemperature"
     * @const
     */
    "ambientTemperature": "ambientTemperature",
    /**
     * value: "probeTemperature"
     * @const
     */
    "probeTemperature": "probeTemperature",
    /**
     * value: "currentLoop1Raw"
     * @const
     */
    "currentLoop1Raw": "currentLoop1Raw",
    /**
     * value: "currentLoop1Mapped"
     * @const
     */
    "currentLoop1Mapped": "currentLoop1Mapped",
    /**
     * value: "currentLoop2Raw"
     * @const
     */
    "currentLoop2Raw": "currentLoop2Raw",
    /**
     * value: "currentLoop2Mapped"
     * @const
     */
    "currentLoop2Mapped": "currentLoop2Mapped",
    /**
     * value: "pmPowerTotal"
     * @const
     */
    "pmPowerTotal": "pmPowerTotal",
    /**
     * value: "pmPhase1Power"
     * @const
     */
    "pmPhase1Power": "pmPhase1Power",
    /**
     * value: "pmPhase2Power"
     * @const
     */
    "pmPhase2Power": "pmPhase2Power",
    /**
     * value: "pmPhase3Power"
     * @const
     */
    "pmPhase3Power": "pmPhase3Power",
    /**
     * value: "pmPhase1PowerFactor"
     * @const
     */
    "pmPhase1PowerFactor": "pmPhase1PowerFactor",
    /**
     * value: "pmPhase2PowerFactor"
     * @const
     */
    "pmPhase2PowerFactor": "pmPhase2PowerFactor",
    /**
     * value: "pmPhase3PowerFactor"
     * @const
     */
    "pmPhase3PowerFactor": "pmPhase3PowerFactor"  };


  return exports;
}));


