/**
 * Samsara API
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SamsaraApi) {
      root.SamsaraApi = {};
    }
    root.SamsaraApi.SensorParam = factory(root.SamsaraApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SensorParam model module.
   * @module models/SensorParam
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SensorParam</code>.
   * @alias module:models/SensorParam
   * @class
   * @param groupId {Integer} Group ID to query.
   * @param sensors {Array.<Integer>} List of sensor IDs to query.
   */
  var exports = function(groupId, sensors) {
    var _this = this;

    _this['groupId'] = groupId;
    _this['sensors'] = sensors;
  };

  /**
   * Constructs a <code>SensorParam</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:models/SensorParam} obj Optional instance to populate.
   * @return {module:models/SensorParam} The populated <code>SensorParam</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('groupId')) {
        obj['groupId'] = ApiClient.convertToType(data['groupId'], 'Integer');
      }
      if (data.hasOwnProperty('sensors')) {
        obj['sensors'] = ApiClient.convertToType(data['sensors'], ['Integer']);
      }
    }
    return obj;
  }

  /**
   * Group ID to query.
   * @member {Integer} groupId
   */
  exports.prototype['groupId'] = undefined;
  /**
   * List of sensor IDs to query.
   * @member {Array.<Integer>} sensors
   */
  exports.prototype['sensors'] = undefined;



  return exports;
}));


