/**
 * Samsara API
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SamsaraApi) {
      root.SamsaraApi = {};
    }
    root.SamsaraApi.TripsParam = factory(root.SamsaraApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TripsParam model module.
   * @module models/TripsParam
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>TripsParam</code>.
   * @alias module:models/TripsParam
   * @class
   * @param groupId {Integer} Group ID to query.
   * @param vehicleId {Integer} Vehicle ID to query.
   * @param startMs {Integer} Beginning of the time range, specified in milliseconds UNIX time.
   * @param endMs {Integer} End of the time range, specified in milliseconds UNIX time.
   */
  var exports = function(groupId, vehicleId, startMs, endMs) {
    var _this = this;

    _this['groupId'] = groupId;
    _this['vehicleId'] = vehicleId;
    _this['startMs'] = startMs;
    _this['endMs'] = endMs;
  };

  /**
   * Constructs a <code>TripsParam</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:models/TripsParam} obj Optional instance to populate.
   * @return {module:models/TripsParam} The populated <code>TripsParam</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('groupId')) {
        obj['groupId'] = ApiClient.convertToType(data['groupId'], 'Integer');
      }
      if (data.hasOwnProperty('vehicleId')) {
        obj['vehicleId'] = ApiClient.convertToType(data['vehicleId'], 'Integer');
      }
      if (data.hasOwnProperty('startMs')) {
        obj['startMs'] = ApiClient.convertToType(data['startMs'], 'Integer');
      }
      if (data.hasOwnProperty('endMs')) {
        obj['endMs'] = ApiClient.convertToType(data['endMs'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * Group ID to query.
   * @member {Integer} groupId
   */
  exports.prototype['groupId'] = undefined;
  /**
   * Vehicle ID to query.
   * @member {Integer} vehicleId
   */
  exports.prototype['vehicleId'] = undefined;
  /**
   * Beginning of the time range, specified in milliseconds UNIX time.
   * @member {Integer} startMs
   */
  exports.prototype['startMs'] = undefined;
  /**
   * End of the time range, specified in milliseconds UNIX time.
   * @member {Integer} endMs
   */
  exports.prototype['endMs'] = undefined;



  return exports;
}));


