/**
 * Samsara API
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'models/TripResponseEndCoordinates', 'models/TripResponseStartCoordinates'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TripResponseEndCoordinates'), require('./TripResponseStartCoordinates'));
  } else {
    // Browser globals (root is window)
    if (!root.SamsaraApi) {
      root.SamsaraApi = {};
    }
    root.SamsaraApi.TripResponseTrips = factory(root.SamsaraApi.ApiClient, root.SamsaraApi.TripResponseEndCoordinates, root.SamsaraApi.TripResponseStartCoordinates);
  }
}(this, function(ApiClient, TripResponseEndCoordinates, TripResponseStartCoordinates) {
  'use strict';




  /**
   * The TripResponseTrips model module.
   * @module models/TripResponseTrips
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>TripResponseTrips</code>.
   * @alias module:models/TripResponseTrips
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>TripResponseTrips</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:models/TripResponseTrips} obj Optional instance to populate.
   * @return {module:models/TripResponseTrips} The populated <code>TripResponseTrips</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('startMs')) {
        obj['startMs'] = ApiClient.convertToType(data['startMs'], 'Integer');
      }
      if (data.hasOwnProperty('startCoordinates')) {
        obj['startCoordinates'] = TripResponseStartCoordinates.constructFromObject(data['startCoordinates']);
      }
      if (data.hasOwnProperty('startLocation')) {
        obj['startLocation'] = ApiClient.convertToType(data['startLocation'], 'String');
      }
      if (data.hasOwnProperty('endMs')) {
        obj['endMs'] = ApiClient.convertToType(data['endMs'], 'Integer');
      }
      if (data.hasOwnProperty('endCoordinates')) {
        obj['endCoordinates'] = TripResponseEndCoordinates.constructFromObject(data['endCoordinates']);
      }
      if (data.hasOwnProperty('endLocation')) {
        obj['endLocation'] = ApiClient.convertToType(data['endLocation'], 'String');
      }
    }
    return obj;
  }

  /**
   * Beginning of the trip in UNIX milliseconds.
   * @member {Integer} startMs
   */
  exports.prototype['startMs'] = undefined;
  /**
   * @member {module:models/TripResponseStartCoordinates} startCoordinates
   */
  exports.prototype['startCoordinates'] = undefined;
  /**
   * Text representation of nearest identifiable location to the start (latitude, longitude) coordinates.
   * @member {String} startLocation
   */
  exports.prototype['startLocation'] = undefined;
  /**
   * End of the trip in UNIX milliseconds.
   * @member {Integer} endMs
   */
  exports.prototype['endMs'] = undefined;
  /**
   * @member {module:models/TripResponseEndCoordinates} endCoordinates
   */
  exports.prototype['endCoordinates'] = undefined;
  /**
   * Text representation of nearest identifiable location to the end (latitude, longitude) coordinates.
   * @member {String} endLocation
   */
  exports.prototype['endLocation'] = undefined;



  return exports;
}));


