/**
 * Samsara API
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SamsaraApi);
  }
}(this, function(expect, SamsaraApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SamsaraApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('addFleetAddress', function() {
      it('should call addFleetAddress successfully', function(done) {
        //uncomment below and update the code to test addFleetAddress
        //instance.addFleetAddress(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFleet', function() {
      it('should call getFleet successfully', function(done) {
        //uncomment below and update the code to test getFleet
        //instance.getFleet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFleetLocations', function() {
      it('should call getFleetLocations successfully', function(done) {
        //uncomment below and update the code to test getFleetLocations
        //instance.getFleetLocations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFleetTrips', function() {
      it('should call getFleetTrips successfully', function(done) {
        //uncomment below and update the code to test getFleetTrips
        //instance.getFleetTrips(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSensors', function() {
      it('should call getSensors successfully', function(done) {
        //uncomment below and update the code to test getSensors
        //instance.getSensors(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSensorsHistory', function() {
      it('should call getSensorsHistory successfully', function(done) {
        //uncomment below and update the code to test getSensorsHistory
        //instance.getSensorsHistory(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSensorsHumidity', function() {
      it('should call getSensorsHumidity successfully', function(done) {
        //uncomment below and update the code to test getSensorsHumidity
        //instance.getSensorsHumidity(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSensorsTemperature', function() {
      it('should call getSensorsTemperature successfully', function(done) {
        //uncomment below and update the code to test getSensorsTemperature
        //instance.getSensorsTemperature(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateVehicles', function() {
      it('should call updateVehicles successfully', function(done) {
        //uncomment below and update the code to test updateVehicles
        //instance.updateVehicles(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
