/**
 * Samsara API
 * # Introduction The Samsara REST API lets you interact with the Samsara Cloud from anything that can send an HTTP request. With the Samsara API you can build powerful applications and custom solutions with sensor data.  Samsara has endpoints available to track and analyze sensors, vehicles, and entire fleets. If you’re familiar with what you can build with a REST API, the following API reference guide will be your go-to resource.  API access to the Samsara cloud is available to all Samsara administrators. If you’d like to try the API, [contact us](https://www.samsara.com/free-trial). The API is currently in beta and may be subject to frequent changes.  # Connecting to the API There are two ways to connect to the API. If you prefer to use the API in Javascript or Python, we supply SDKs which you can download here: [Javascript SDK](https://github.com/samsarahq/samsara-js), [Python SDK](https://github.com/samsarahq/samsara-python).  If you’d rather use another language to interact with the Samsara API, the endpoints and examples are in the reference guide below.  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'models/GroupParam', 'models/InlineResponse2002', 'models/ErrorResponse', 'models/HistoryParam', 'models/SensorHistoryResponse', 'models/HumidityResponse', 'models/SensorParam', 'models/TemperatureResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../models/GroupParam'), require('../models/InlineResponse2002'), require('../models/ErrorResponse'), require('../models/HistoryParam'), require('../models/SensorHistoryResponse'), require('../models/HumidityResponse'), require('../models/SensorParam'), require('../models/TemperatureResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.SamsaraApi) {
      root.SamsaraApi = {};
    }
    root.SamsaraApi.SensorsApi = factory(root.SamsaraApi.ApiClient, root.SamsaraApi.GroupParam, root.SamsaraApi.InlineResponse2002, root.SamsaraApi.ErrorResponse, root.SamsaraApi.HistoryParam, root.SamsaraApi.SensorHistoryResponse, root.SamsaraApi.HumidityResponse, root.SamsaraApi.SensorParam, root.SamsaraApi.TemperatureResponse);
  }
}(this, function(ApiClient, GroupParam, InlineResponse2002, ErrorResponse, HistoryParam, SensorHistoryResponse, HumidityResponse, SensorParam, TemperatureResponse) {
  'use strict';

  /**
   * Sensors service.
   * @module client/SensorsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new SensorsApi. 
   * @alias module:client/SensorsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getSensors operation.
     * @callback module:client/SensorsApi~getSensorsCallback
     * @param {String} error Error message, if any.
     * @param {module:models/InlineResponse2002} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * /sensors/list
     * Get sensor objects. This method returns a list of the sensor objects in the Samsara Cloud and information about them.
     * @param {String} accessToken Samsara API access token.
     * @param {module:models/GroupParam} groupParam Group ID to query.
     * @param {module:client/SensorsApi~getSensorsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/InlineResponse2002}
     */
    this.getSensors = function(accessToken, groupParam, callback) {
      var postBody = groupParam;

      // verify the required parameter 'accessToken' is set
      if (accessToken == undefined || accessToken == null) {
        throw "Missing the required parameter 'accessToken' when calling getSensors";
      }

      // verify the required parameter 'groupParam' is set
      if (groupParam == undefined || groupParam == null) {
        throw "Missing the required parameter 'groupParam' when calling getSensors";
      }


      var pathParams = {
      };
      var queryParams = {
        'access_token': accessToken
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse2002;

      return this.apiClient.callApi(
        '/sensors/list', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getSensorsHistory operation.
     * @callback module:client/SensorsApi~getSensorsHistoryCallback
     * @param {String} error Error message, if any.
     * @param {module:models/SensorHistoryResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * /sensors/history
     * Get historical data for specified sensors. This method returns a set of historical data for the specified sensors in the specified time range and at the specified time resolution.
     * @param {String} accessToken Samsara API access token.
     * @param {module:models/HistoryParam} historyParam Group ID, time range and resolution, and list of sensor ID, field pairs to query.
     * @param {module:client/SensorsApi~getSensorsHistoryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/SensorHistoryResponse}
     */
    this.getSensorsHistory = function(accessToken, historyParam, callback) {
      var postBody = historyParam;

      // verify the required parameter 'accessToken' is set
      if (accessToken == undefined || accessToken == null) {
        throw "Missing the required parameter 'accessToken' when calling getSensorsHistory";
      }

      // verify the required parameter 'historyParam' is set
      if (historyParam == undefined || historyParam == null) {
        throw "Missing the required parameter 'historyParam' when calling getSensorsHistory";
      }


      var pathParams = {
      };
      var queryParams = {
        'access_token': accessToken
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SensorHistoryResponse;

      return this.apiClient.callApi(
        '/sensors/history', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getSensorsHumidity operation.
     * @callback module:client/SensorsApi~getSensorsHumidityCallback
     * @param {String} error Error message, if any.
     * @param {module:models/HumidityResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * /sensors/humidity
     * Get humidity for requested sensors. This method returns the current relative humidity for the requested sensors.
     * @param {String} accessToken Samsara API access token.
     * @param {module:models/SensorParam} sensorParam Group ID and list of sensor IDs to query.
     * @param {module:client/SensorsApi~getSensorsHumidityCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/HumidityResponse}
     */
    this.getSensorsHumidity = function(accessToken, sensorParam, callback) {
      var postBody = sensorParam;

      // verify the required parameter 'accessToken' is set
      if (accessToken == undefined || accessToken == null) {
        throw "Missing the required parameter 'accessToken' when calling getSensorsHumidity";
      }

      // verify the required parameter 'sensorParam' is set
      if (sensorParam == undefined || sensorParam == null) {
        throw "Missing the required parameter 'sensorParam' when calling getSensorsHumidity";
      }


      var pathParams = {
      };
      var queryParams = {
        'access_token': accessToken
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = HumidityResponse;

      return this.apiClient.callApi(
        '/sensors/humidity', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getSensorsTemperature operation.
     * @callback module:client/SensorsApi~getSensorsTemperatureCallback
     * @param {String} error Error message, if any.
     * @param {module:models/TemperatureResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * /sensors/temperature
     * Get temperature for requested sensors. This method returns the current ambient temperature (and probe temperature if applicable) for the requested sensors.
     * @param {String} accessToken Samsara API access token.
     * @param {module:models/SensorParam} sensorParam Group ID and list of sensor IDs to query.
     * @param {module:client/SensorsApi~getSensorsTemperatureCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/TemperatureResponse}
     */
    this.getSensorsTemperature = function(accessToken, sensorParam, callback) {
      var postBody = sensorParam;

      // verify the required parameter 'accessToken' is set
      if (accessToken == undefined || accessToken == null) {
        throw "Missing the required parameter 'accessToken' when calling getSensorsTemperature";
      }

      // verify the required parameter 'sensorParam' is set
      if (sensorParam == undefined || sensorParam == null) {
        throw "Missing the required parameter 'sensorParam' when calling getSensorsTemperature";
      }


      var pathParams = {
      };
      var queryParams = {
        'access_token': accessToken
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = TemperatureResponse;

      return this.apiClient.callApi(
        '/sensors/temperature', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
